### ISSUE TITLE
player.animate() and player.emoji() does not work

### ISSUE THREAD

**Issue by dr-mister-mike** [cryptovoxels/scripting-bundle#26]
Script on a button:

feature.on('click', (e)=> {
  e.player.emote("😋") //does not do anything
  e.player.animate('Dance') //does not work too
})

Chrome:
Version 95.0.4638.69 (Official Build) (x86_64)

**Comment by Benjythebee** [comment]
Lol, a bit late to the party but `player.emote()` has been fixed!

`animate()` has been deprecated however

commit 63bc3d72fe46435e98c393016dc0ad34a09f9642
